baseurl = "https://reisei.ru"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
title = "Aleksandr Chapkin"

paginate = 20
canonifyurls = true

#pygmentsstyle = "bw"
#pygmentscodefences = true
#pygmentscodefencesguesssyntax = true

disqusShortname = "reisei"

relativeURLs = true

googleAnalytics = "UA-37400922-4"

[blackfriday]
  hrefTargetBlank = true

[params]
    author = "Aleksandr Chapkin"
    info = "Linux System Administrator, DevOps enthusiast"
    keywords = "blog,personal,linux,devops"
    avatarurl = "/images/avatar.png"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    hidecredits = true
    hidecopyright = true

    rtl = false
    math = true

    #custom_css = ["css/nonacademicons.css", "css/nonacademicons.min.css"]
    custom_css = ["css/nonacademicons.min.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/reisei/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/reisei/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/achapkin/"
[[params.social]]
    name = "Tumblr"
    icon = "fa fa-tumblr fa-2x"
    weight = 4
    url = "https://coffee-hedgehog.ru"
[[params.social]]
    name = "Lichess"
    icon = "nai nai-lichess nai-2x"
    weight = 5
    url = "https://lichess.org/@/reisei"
